TOP = ../..
include $(TOP)/configure/CONFIG

#DIRS := $(DIRS) $(filter-out $(DIRS), $(wildcard *mysql*))
DIRS := mysql-connector-c-6_1_5 mysql-connector-c++-1_1_4

include $(TOP)/configure/RULES_DIRS
